imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    
parameters:
    session.storage.native.class: Admin\MainBundle\Session\Storage
    json_generator:
      newsDir:    ""
      staticDir:  ""
      uploadDir:  ""
      galleryDir: ""
    uploader:
      upload_dir:   "../../front-end/app/content/gallery"
      token:        "1oiCZN24qL237vL12CZN24qL237"
      img_types:
        0: "jpg"
        1: "JPG"
        2: "jpeg"
        3: "JPEG"
        4: "jpe"
        5: "JPE"
        6: "png"
        7: "PNG"
        8: "gif"
        9: "GIF"
      video_types:
        0: "avi"
        1: "AVI"
        2: "mp4"
        3: "MP4"
        4: "m4v"
        5: "M4V"
        6: "mkv"
        7: "MKV"
        8: "wmv"
        9: "WMV"
      glob_options:
        max_width:            160
        max_height:           160
        no_cache:             false
        no_video_thumbs:      true
        max_original_width:   1024
        max_original_height:  768
        thumbnail:
          max_width:  160
          max_height: 160
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        options:
           1002:  "SET NAMES 'UTF8'"
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
    logout.handler:
        class: Helpers\LogoutHandler
        arguments: [ "@router_listener" ]
    locale_listener:
        class: Helpers\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    session.storage.native:
        class:     %session.storage.native.class%
        arguments: [%session.storage.options%, @service_container]