api_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: APIMainBundle:Default:index }

api_add_order:
    pattern:  /addOrder
    defaults: { _controller: APIMainBundle:Order:addOrder }

