#parameters:
##    admin_main.example.class: Admin\MainBundle\Example
#
#services:
##    admin_main.example:
##        class: %admin_main.example.class%
##        arguments: [@service_id, "plain_value", %parameter%]
parameters:
  user_provider.class: Admin\MainBundle\Security\UserProvider
  user.class: Admin\MainBundle\Entity\Admin

services:
  user_provider:
    class: %user_provider.class%
    arguments: ['@doctrine', %user.class%]