parameters:
#    admin_order.example.class: Admin\OrderBundle\Example

services:
#    admin_order.example:
#        class: %admin_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
